### PR TITLE
Added Japanese Localize

### PR DESCRIPTION
**Pull request by NeetShin**
Hi John! I added Japanese localize files
- ja.xliff
- (InfoPlist.strings)
- (LaunchScreen.strings)
- (Localizable.strings)
- (Main.strings)

They're following latest Mastodon's branch, so correct! I hope Amaroq will get more users!
Thanks <3

### CODE REVIEW

**Comment by NeetShin** [comment]
Line 1961 and line 2026 are intentional empty. 
Because this is of subject abbreviation in Japanese!

**Comment by NeetShin** [comment]
Yes, line 195 and line 234 are subject omit in Japanese.

**Comment by ReticentJohn** [comment]
This looks fantastic, I'll give it a run on my device and then merge in once the email is fixed. Thank you so much for the help!! <3

**Comment by NeetShin** [comment]
Oh! I'm sorry >_<
I fixed it!

**Pull request merged**
